version: '3.5'

services:
  app:
    build:
      context: .
      args:
        NEXT_URL: 'http://127.0.0.1:3000'
        DIRECTUS_URL: 'http://host.docker.internal:8055'
        ASSETS_URL: 'http://host.docker.internal:8055/assets'
        ASSETS_PROTOCOL: 'http'
        ASSETS_HOST: 'host.docker.internal'
        ASSETS_PORT: '8055'
        ASSETS_PATH: '/assets/**'
        DIRECTUS_PREVIEW_SECRET: '26Fi^quI9C'
    container_name: page-block-builder-app
    ports:
      - '3000:3000'
    networks:
      - clifford-solutions-directus
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  storybook:
    build:
      context: .
    container_name: page-block-builder-storybook
    command: npm run storybook
    ports:
      - '6006:6006'

networks:
  clifford-solutions-directus:
    name: clifford-solutions-directus
    external: true
