version: '3.5'

services:
  app:
    build:
      context: .
    container_name: page-block-builder-app
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - page-block-builder-directus_default
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  storybook:
    build:
      context: .
    container_name: page-block-builder-storybook
    command: npm run storybook
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules

networks:
  page-block-builder-directus_default:
    name: page-block-builder-directus_default
    external: true
