version: '3.5'

services:
  app:
    build:
      context: .
    container_name: clifford-solutions-fe-app
    command: npm run build && npm run start
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - clifford-solutions-directus
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  storybook:
    build:
      context: .
    container_name: clifford-solutions-storybook
    command: npm run storybook
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules

networks:
  clifford-solutions-directus:
    name: clifford-solutions-directus
    external: true
